#include "minishell.h" 

void ft_intro()
{	ft_putendl("																										");
	ft_putendl("	* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  *");
	ft_putendl("	*                                                                                                  *");
	ft_putendl("	*                                                                                                  *");
	ft_putendl("	*                                                                                                  *");
	ft_putstr("	*   ▄▄▄▄███▄▄▄▄    ▄█  ███▄▄▄▄    ▄█     ▄████████    ");
	ft_putstr("\033[0;31m");
	ft_putstr("▄█    █▄       ▄████████  ▄█        ▄█");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ▄██▀▀▀███▀▀▀██▄ ███  ███▀▀▀██▄ ███    ███    ███   ");
	ft_putstr("\033[0;31m");
	ft_putstr("███    ███     ███    ███ ███       ███");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ███   ███   ███ ███▌ ███   ███ ███▌   ███    █▀    ");
	ft_putstr("\033[0;31m");
	ft_putstr("███    ███     ███    █▀  ███       ███");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ███   ███   ███ ███▌ ███   ███ ███▌   ███         ");
	ft_putstr("\033[0;31m");
	ft_putstr("▄███▄▄▄▄███▄▄  ▄███▄▄▄     ███       ███");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ███   ███   ███ ███▌ ███   ███ ███▌ ▀███████████ ");
	ft_putstr("\033[0;31m");
	ft_putstr("▀▀███▀▀▀▀███▀  ▀▀███▀▀▀     ███       ███");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ███   ███   ███ ███  ███   ███ ███           ███   ");
	ft_putstr("\033[0;31m");
	ft_putstr("███    ███     ███    █▄  ███       ███");
	ft_putstr("\033[0m");
	ft_putendl("       *");
	ft_putstr("	* ███   ███   ███ ███  ███   ███ ███     ▄█    ███   ");
	ft_putstr("\033[0;31m");
	ft_putstr("███    ███     ███    ███ ███▌    ▄ ███▌    ▄");
	ft_putstr("\033[0m");
	ft_putendl(" *");
	ft_putstr("	*  ▀█   ███   █▀  █▀    ▀█   █▀  █▀    ▄████████▀    ");
	ft_putstr("\033[0;31m");
	ft_putstr("███    █▀      ██████████ █████▄▄██ █████▄▄██");
	ft_putstr("\033[0m");
	ft_putendl(" *");
	ft_putendl("	*                                                                                                  *");
	ft_putendl("	*                                                                                                  *");
	ft_putendl("	*                                                                                                  *");
	ft_putendl("	* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  *");
}